ueberwachungspaket/views/consultation.py
from random import shuffle
from json import load
from flask import (Blueprint, render_template, request, jsonify,
                   send_from_directory)
from sqlalchemy import and_
from config import *
from config.main import *
from config.mail import *
from database.models import Opinion
from database import db_session

mod = Blueprint("consultation", __name__, url_prefix="/konsultation")
page_size = 35


@mod.route("/")
def index():
    with open("ueberwachungspaket/data/quotes.json", "r") as json_file:
        quotes = load(json_file)
    shuffle(quotes)
    query = db_session.query(Opinion).order_by(Opinion.originality.desc(), Opinion.date.desc())
    opinions_count = query.count()
    opinions = query.limit(page_size).all()

    return render_template(
        "consultation/index.html",
        quotes=quotes,
        opinions=opinions,
        opinions_count=opinions_count
    )


@mod.route("/load")
def consultation_load():
    page_index = request.args.get("pageIndex", 0, type=int)
    sort_key = request.args.get("sortKey")
    filter_origin = request.args.get("filterOrigin")
    filter_topic = request.args.get("filterTopic")
    filter_name = request.args.get("filterName")

    query = db_session.query(Opinion)

    if sort_key:
        if sort_key == "name":
            query = query.order_by(Opinion.name, Opinion.originality.desc())
        if sort_key == "-name":
            query = query.order_by(Opinion.name.desc(), Opinion.originality.desc())
        elif sort_key == "date":
            query = query.order_by(Opinion.date, Opinion.originality.desc())
        elif sort_key == "-date":
            query = query.order_by(Opinion.date.desc(), Opinion.originality.desc())
        elif sort_key == "-originality":
            query = query.order_by(Opinion.originality, Opinion.date.desc())
        else:
            query = query.order_by(Opinion.originality.desc(), Opinion.date.desc())

    if filter_topic:
        if filter_topic == "bundestrojaner":
            query = query.filter_by(addresses_bundestrojaner=True)
        elif filter_topic == "netzsperren":
            query = query.filter_by(addresses_netzsperren=True)
        elif filter_topic == "vds-video":
            query = query.filter_by(addresses_vds_video=True)
        elif filter_topic == "ueberwachung-strassen":
            query = query.filter_by(addresses_ueberwachung_strassen=True)
        elif filter_topic == "vds-quickfreeze":
            query = query.filter_by(addresses_vds_quickfreeze=True)
        elif filter_topic == "anonyme-simkarten":
            query = query.filter_by(addresses_anonyme_simkarten=True)
        elif filter_topic == "imsi-catcher":
            query = query.filter_by(addresses_imsi_catcher=True)
        elif filter_topic == "lauschangriff-auto":
            query = query.filter_by(addresses_lauschangriff_auto=True)

    if filter_origin:
        if filter_origin == "bmi":
            query = query.filter(and_(Opinion.link_bmi_pdf.isnot(None), Opinion.link_bmi_pdf != ""))
        elif filter_origin == "bmj":
            query = query.filter(and_(Opinion.link_bmj_pdf.isnot(None), Opinion.link_bmj_pdf != ""))

    if filter_name:
        query = query.filter(Opinion.name.ilike("%{}%".format(filter_name)))

    opinions_count = query.count()
    opinions = query.slice(page_index * page_size, (page_index + 1) * page_size).all()
    opinions = [opinion.serialize() for opinion in opinions]
    return jsonify(opinions=opinions, count=opinions_count)


@mod.route("/stats")
def consultation_stats():
    query = db_session.query(Opinion)
    stats = {
        "addressesBundestrojaner": query.filter_by(addresses_bundestrojaner=True).count(),
        "addressesNetzsperren": query.filter_by(addresses_netzsperren=True).count(),
        "addressesVdsVideo": query.filter_by(addresses_vds_video=True).count(),
        "addressesUeberwachungStrassen": query.filter_by(addresses_ueberwachung_strassen=True).count(),
        "addressesVdsQuickfreeze": query.filter_by(addresses_vds_quickfreeze=True).count(),
        "addressesAnonymeSimkarten": query.filter_by(addresses_anonyme_simkarten=True).count(),
        "addressesImsiCatcher": query.filter_by(addresses_imsi_catcher=True).count(),
        "addressesLauschangriffAuto": query.filter_by(addresses_lauschangriff_auto=True).count()
    }
    return jsonify(stats=stats)


@mod.route("/showpdf/bmi/<int:fid>")
def showpdf_bmi(fid):
    resp = send_from_directory(PDF_FOLDER, str(fid) + "_bmi.pdf")
    resp.headers["Content-Disposition"] = "inline; filename=" + str(fid) + "_bmi.pdf"
    return resp


@mod.route("/showpdf/bmj/<int:fid>")
def showpdf_bmj(fid):
    resp = send_from_directory(PDF_FOLDER, str(fid) + "_bmj.pdf")
    resp.headers["Content-Disposition"] = "inline; filename=" + str(fid) + "_bmj.pdf"
    return resp

ueberwachungspaket/views/general.py
from random import shuffle
from json import load
from flask import Blueprint, render_template, abort, request, jsonify
from sqlalchemy import func
from sqlalchemy.exc import IntegrityError
from config import TWILIO_NUMBERS, ACTIVISM_LIST_POST_URL, ACTIVISM_LIST_POST_REFERER
from database.models import Representatives, Opinion, ConsultationSender, Activist
from database import db_session
from datetime import datetime
import requests

mod = Blueprint("general", __name__)
reps = Representatives()


@mod.route("/")
def index():
    with open("ueberwachungspaket/data/quotes_2.0.json", "r") as json_file:
        quotes = load(json_file)
    shuffle(quotes)
    consultation_count = 9143 #db_session.query(func.count(ConsultationSender.date_validated)).one()[0]
    opinions = db_session.query(Opinion).count()
    return render_template(
        "general/index.html",
        quotes=quotes,
        opinion_count=opinions,
        consultation_count=consultation_count
    )


#@mod.route("/politiker/")
def representatives():
    reps_random = reps.representatives + reps.government
    shuffle(reps_random)
    return render_template(
        "act/representatives.html",
        reps=reps_random
    )


#@mod.route("/p/<prettyname>/")
def representative(prettyname):
    rep = reps.get_representative_by_name(prettyname)
    if rep:
        return render_template(
            "act/representative.html",
            rep=rep,
            twilio_number=TWILIO_NUMBERS[0]
        )
    else:
        abort(404)


@mod.route("/weitersagen/")
def share():
    return render_template("general/share.html")


@mod.route("/unterstützer/")
def supporters():
    return render_template("general/supporters.html")


@mod.route("/faq/")
def faq():
    return render_template("general/faq.html")


@mod.route("/datenschutz/")
def privacy():
    return render_template("general/privacy.html")

#@mod.route("/join/", methods=["POST"])
def join():
    email = request.form.get('email')
    phone = request.form.get('phonenumber')

    if not email:
        abort(400)

    activist = Activist(email, phone, datetime.now())

    try:
        db_session.add(activist)
        db_session.commit()
    except IntegrityError:
        return jsonify({'status': 'error', 'reason': 'already_subscribed'})

    requests.post(ACTIVISM_LIST_POST_URL, data={'email': email}, headers={'referer': ACTIVISM_LIST_POST_REFERER})

    return jsonify({'status': 'success', 'reason': ''})

ueberwachungspaket/templates/_foot.html
<script language="javascript" type="text/javascript" src="{{ url_for('static', filename='js/jquery-3.1.1.min.js') }}"></script>
<script language="javascript" type="text/javascript" src="{{ url_for('static', filename='js/jquery-ui.js') }}"></script>
<script language="javascript" type="text/javascript" src="{{ url_for('static', filename='js/sms-link.min.js') }}"></script>
<script language="javascript" type="text/javascript" src="{{ url_for('static', filename='js/slick.min.js') }}"></script>
<script language="javascript" type="text/javascript" src="{{ url_for('static', filename='js/chart.min.js') }}"></script>
<script language="javascript" type="text/javascript" src="{{ url_for('static', filename='js/site.js') }}"></script>
<!-- Piwik -->
<script type="text/javascript">
  var _paq = _paq || [];
  // tracker methods like "setCustomDimension" should be called before "trackPageView"
  _paq.push(['disableCookies']);
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//matomo.epicenter.works/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', '7']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<!-- End Piwik Code -->

ueberwachungspaket/templates/_footer.html
<ul>
    <li><a href="https://epicenter.works/kontakt">Impressum</a></li>
    <li><a href="https://epicenter.works/kontakt">Presse</a></li>
    <li><a href="{{ url_for('general.privacy') }}">Datenschutz</a></li>
</ul>

ueberwachungspaket/templates/_head.html
<meta charset="UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
<meta name="author" content="epicenter.works" />
<meta name="description" content="Sicherheit statt Überwachung!" />
<meta name="keywords" content="überwachung, vorratsdaten" />

<meta property="og:title" content="{{ config['PROJECT_NAME'] }}" />
<meta property="og:image" content="{{ url_for('static', filename='img/thumbnail.jpg', _external=True) }}" />
<meta property="og:type" content="website" />
<meta property="og:url" content="https://überwachungspaket.at/" />
<meta property="og:description" content="Sicherheit statt Überwachung" />
<meta property="og:locale" content="de_AT" />
<meta property="og:site_name" content="epicenter.works"/>

<meta name="twitter:title" content="{{ config['PROJECT_NAME'] }}" />
<meta name="twitter:image" content="{{ url_for('static', filename='img/thumbnail.jpg', _external=True) }}" />
<meta name="twitter:card" content="summary" />
<meta name="twitter:url" content="https://überwachungspaket.at/" />
<meta name="twitter:description" content="Sicherheit statt Überwachung!" />
<meta name="twitter:site" content="@epicenter_works" />

<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/normalize.css') }}" />
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/font-awesome.min.css') }}" />
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}" />
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/jquery-ui.css') }}" />
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/slick.css') }}" />
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/slick-theme.css') }}" />
<link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='img/favicon.ico') }}" />

ueberwachungspaket/templates/consultation.html
{% extends "layout.html" %}
{% set active_page = "consultation" %}

{% block title %}
	<title>Konsultation | {{ config['PROJECT_NAME'] }}</title>
{% endblock title %}

{% block content %}
<section id="quotes">
	<div class="container">
		<h2>Noch nie war eine Begutachtung so eindeutig</h2>
		{% include "consultation_quotes.html" %}
		<h2 class="indent">Welche Themen von den meisten Stellungnahmen abgelehnt wurden</h2>
		<canvas id="barChart" class="indent" height="80"></canvas>
	</div>
</section>
<section id="table">
	<div class="container">
		<h2>Alle Stellungnahmen im Detail</h2>
		<div id="settings" class="indent">
			<form action="javascript:void(0);" autocomplete="off">
				<div class="row">
					<input id="filterBmi" class="hidden" name="filterOrigin" value="bmi" type="radio" />
					<label for="filterBmi">BMI</label>
					<input id="filterBmj" class="hidden" name="filterOrigin" value="bmj" type="radio" />
					<label for="filterBmj">BMJ</label>
					<input id="filterBoth" class="hidden" name="filterOrigin" value="both" type="radio" checked="checked" />
					<label for="filterBoth">beide</label>
				</div>
				<div class="row">
					<select name="filterTopic">
						<option value="all" selected="selected">Alle Themen</option>
						<option value="bundestrojaner">Bundestrojaner</option>
						<option value="netzsperren">Netzsperren</option>
						<option value="vds-video">Vorratsdatenspeicherung für Videoüberwachung</option>
						<option value="ueberwachung-strassen">Vollüberwachung auf Österreichs Straßen</option>
						<option value="vds-quickfreeze">Quickfreeze</option>
						<option value="anonyme-simkarten">Anonyme Simkarten</option>
						<option value="imsi-catcher">IMSI-Catcher</option>
						<option value="lauschangriff-auto">Lauschangriff im Auto</option>
					</select>
				</div>
				<div class="row">
					<input name="filterName" type="text" placeholder="Namenssuche">
					<input id="filterNameButton" class="btn" type="button" value="Suchen" />
				</div>
			</form>
			<p class="center"><span id="opinionsCount">{{ opinions_count }}</span> öffentliche Einträge gefunden</p>
		</div>
		<div style="overflow-x:auto;">
			<table id="consultationTable" class="indent">
				<thead>
					<tr>
						<th class="left absorbing sortable" data-sort-key="name">Name</th>
						<th class="sortable" data-sort-key="date">Datum</th>
						<th>BMI</th>
						<th>BMJ</th>
						<th>Themen</th>
						<th class="sortable" data-sort-key="originality">Originalität</th>
					</tr>
				</thead>
				<tbody>
					{% for opinion in opinions %}
					<tr>
						<td>{{ opinion.name_pretty() }}</td>
						<td class="center">{{ opinion.date_pretty() }}</td>
						<td class="center">{% if opinion.link_bmi_pdf -%}<a href="{{ opinion.link_bmi_pdf }}"><i class="fa fa-file-pdf-o" aria-hidden="true"></i></a>{% endif -%}</td>
						<td class="center">{% if opinion.link_bmj_pdf -%}<a href="{{ opinion.link_bmj_pdf }}"><i class="fa fa-file-pdf-o" aria-hidden="true"></i></a>{% endif -%}</td>
						<td class="center">
							<img src="{{ url_for('static', filename='img/icons/' + ('green' if opinion.addresses_bundestrojaner else 'gray') + '/trojaner.png') }}" alt="" class="indicator" title="Bundestrojaner" />&nbsp;<img src="{{ url_for('static', filename='img/icons/' + ('green' if opinion.addresses_netzsperren else 'gray') + '/netzsperren.png') }}" alt="" class="indicator" title="Netzsperren" />&nbsp;<img src="{{ url_for('static', filename='img/icons/' + ('green' if opinion.addresses_vds_video else 'gray') + '/totalevideoueberwachung.png') }}" alt="" class="indicator" title="Vorratsdatenspeicherung für Videoüberwachung" />&nbsp;<img src="{{ url_for('static', filename='img/icons/' + ('green' if opinion.addresses_ueberwachung_strassen else 'gray') + '/verkehrsueberwachung.png') }}" alt="" class="indicator" title="Vollüberwachung auf Österreichs Straßen" />&nbsp;<img src="{{ url_for('static', filename='img/icons/' + ('green' if opinion.addresses_vds_quickfreeze else 'gray') + '/vorratsdaten.png') }}" alt="" class="indicator" title="Quickfreeze" />&nbsp;<img src="{{ url_for('static', filename='img/icons/' + ('green' if opinion.addresses_anonyme_simkarten else 'gray') + '/sim-id.png') }}" alt="" class="indicator" title="Anonyme Simkarten" />&nbsp;<img src="{{ url_for('static', filename='img/icons/' + ('green' if opinion.addresses_imsi_catcher else 'gray') + '/imsicatcher.png') }}" alt="" class="indicator" title="IMSI-Catcher" />&nbsp;<img src="{{ url_for('static', filename='img/icons/' + ('green' if opinion.addresses_lauschangriff_auto else 'gray') + '/lauschangriffauto.png') }}" alt="" class="indicator" title="Lauschangriff im Auto" />
						</td>
						<td class="center">{{ opinion.originality_pretty() }}{% if opinion.comment -%}<i class="fa fa-chevron-circle-down commentOpener" data-comment="{{ opinion.id }}" aria-hidden="true"></i>{% endif -%}</td>
					</tr>
					{% if opinion.comment -%}
					<tr class="comment" id="comment{{ opinion.id }}">
						<td colspan="6">{{ opinion.comment }}</td>
					</tr>
					{% endif -%}
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
</section>
{% endblock %}

ueberwachungspaket/templates/consultation_quotes.html
<div class="indent" id="quotes-carousel">
{% for quote in quotes %}
{% if quote.slider -%}
	<div>
		<div class="slide-center">
			<div class="avatar">
				{% if quote.logo -%}
				<img src="{{ url_for('static', filename='img/quote/' + quote.logo) }}" alt="" />
				{% else -%}
				<img src="{{ url_for('static', filename='img/quote/user.jpg') }}" alt="" />
				{% endif -%}
			</div>
			<div class="avtxt">
				<strong>{{ quote.name }}</strong>
				<p>{{ quote.text|safe }}</p>
				<a href="{{ quote.url }}" class="small"><i class="fa fa-file-pdf-o" aria-hidden="true"></i> Stellungnahme lesen</a>
			</div>
		</div>
	</div>
{% endif -%}
{% endfor %}
</div>

ueberwachungspaket/templates/faq.html
{% extends "layout.html" %}
{% set active_page = "faq" %}

{% block title %}
	<title>Häufig gestellte Fragen | {{ config['PROJECT_NAME'] }}</title>
{% endblock title %}

{% block content %}
	<section class="chat">
		<div class="container">
			<h1>Häufig gestellte Fragen</h1>
			<h2>An der Konsultation teilnehmen</h2>
			<ul>
				<li>
					<div class="avtxt">
					<h3>Was ist eine Konsultation/Begutachtung?</h3>
					</div>
				</li>
				<li>
					<p>Die Konsultation zu einem Gesetzesvorhaben wird in Österreich auch Begutachtung genannt. Dabei holen die zuständigen Ministerien zu ihren Gesetzesentwürfen in Form von Stellungnahmen Meinungen und Analysen zu ihren Gesetzesentwürfen ein. Im Idealfall werden die Gesetzesentwürfe dann anhand dieser Rückmeldungen überarbeitet und von der Regierung als Regierungsvorlage im Parlament eingereicht.</p>
				</li>
				<li>
					<div class="avtxt">
						<h3>Warum kann ich meine Stellungnahmen nicht anonym abgeben?</h3>
					</div>
				</li>
				<li>
					<p>Als Verein, der Privatsphäre verteidigt, würden wir diese Möglichkeit gerne anbieten. Allerdings akzeptiert das Parlament keine anonymen Stellungnahmen und veröffentlicht die Namen der Einreichenden. Darauf haben wir leider keinen Einfluss.</p>
				</li>
				<li>
					<div class="avtxt">
						<h3>Kann ich meine Stellungnahme vor dem Absenden noch bearbeiten?</h3>
					</div>
				</li>
				<li>
					<p>Ja! Individuelle Abänderungen der Stellungnahmen sind sogar explizit erwünscht. Wir wollen es mit unserem Tool so einfach wie möglich machen am Gesetzgebungsprozess in Österreich teilzunehmen. Dazu stellen wir Textvorschläge zur Verfügung, aber das Begutachtungsverfahren lebt von der Vielfalt der Argumenten. Wenn du dich also bei einem Thema besser auskennst oder gewisse Aspekte anders siehst, kannst du auf der zweiten Seite deine Stellungnahme noch ergänzen.</p>
				</li>
				<li>
					<div class="avtxt">
						<h3>Ich finde gut, dass ihr euch gegen mehr Überwachung einsetzt, bin aber nicht mit allen Punkten einverstanden.</h3>
					</div>
				</li>
				<li>
					<p>Sehr gut! Wir haben alle, für uns relevanten, Punkte aus den Ministerialentwürfen kommentiert, aber letztlich kommt es auf deine persönliche Meinung an. Deshalb kannst du jeden der einzelnen Punkte per Mausklick abwählen. Oder eigene hinzufügen, siehe oben.</p>
				</li>
				<li>
					<div class="avtxt">
						<h3>Ich will meine bereits abgegebene Stellungnahme nachträglich abändern, geht das?</h3>
					</div>
				</li>
				<li>
					<p>Sehr gut! Wir haben alle, für uns relevanten, Punkte aus den Ministerialentwürfen kommentiert, aber letztlich kommt es auf deine persönliche Meinung an. Deshalb kannst du jeden der einzelnen Punkte per Mausklick abwählen. Oder eigene hinzufügen, siehe oben.</p>
				</li>
				<li>
					<div class="avtxt">
						<h3>Ich will meine bereits abgegebene Stellungnahme nachträglich abändern, geht das?</h3>
					</div>
				</li>
				<li>
					<p>Ja, das kannst du. Jedoch nicht über unsere Seite. Wir haben uns aus Gründen der Spamvorbeugung dazu entschlossen, nachträgliche Änderungen nicht über unsere Seite abzuwickeln. Wenn du deine Stellungnahme also abändern willst, musst du dir die Texte kopieren, abändern, ein PDF generieren (z.B. mithilfe von Libre Office) und dieses per Mail sowohl an das zuständige Ministerium (<a href="mailto:bmi-III-1@bmi.gv.at">BMI</a> bzw. <a href="mailto:team.s@bmj.gv.at">BMJ</a>) als auch ans <a href="mailto:begutachtungsverfahren@parlament.gv.at">Parlament</a> senden.</p>
				</li>
				<li>
					<div class="avtxt">
						<h3>Wo werden die abgegebenen Stellungnahmen veröffentlicht?</h3>
					</div>
				</li>
				<li>
					<p>Alle Begutachtungsverfahren und Stellungnahmen sind auf dem Website des Parlaments unter <a href="https://www.parlament.gv.at/PAKT/MESN/">den Begutachtungen</a> zu finden. Die beiden aktuellen Entwürfe zum Überwachungspaket findet man unter dem <a href="https://www.parlament.gv.at/PAKT/VHG/XXV/ME/ME_00325/index.shtml">Strafprozessrechtsänderungsgesetz</a> bzw. dem <a href="https://www.parlament.gv.at/PAKT/VHG/XXV/ME/ME_00326/index.shtml">Bundesgesetz mit dem  das Sicherheitspolizeigesetz, das Bundesstraßen-Mautgesetz, die Straßenverkehrsordnung und das Telekommunikationsgesetz geändert werden</a> online.</p>
				</li>
			</ul>
			<h2>Anderes</h2>
			<ul>
				<li>
					<div class="avtxt">
						<h3>Wer seid ihr?</h3>
					</div>
				</li>
				<li>
					<p>
						Diese Kampagne wurde initiiert von <a href="https://epicenter.works/" target="_blank">epicenter.works</a> (vormals AKVorrat), einem Verein, der sich für die Wahrung von Grundrechten im digitalen Zeitalter einsetzt. Es gibt einige Organisationen, die diese Kampagne gegen das Überwachungspaket unterstützen. Gemäß unserem Slogan "Zivilgesellschaft wirkt!" sind wir offen für weitere Kooperationen. Falls Ihre Organisation beitragen möchte, wenden Sie sich bitte an uns: <a href="https://epicenter.works/kontakt" target="_blank">https://epicenter.works/kontakt</a>
					</p>
				</li>
				<li>
					<div class="avtxt">
						<h3>Warum macht ihr das?</h3>
					</div>
				</li>
				<li>
					<p>Weil wir uns Demokratie und Freiheit nicht nehmen lassen wollen.</p>
				</li>
				<li>
					<div class="avtxt">
						<h3>Wer finanziert euch?</h3>
					</div>
				</li>
				<li>
					<p>
						Der Großteil unseres Budgets kommt von Einzelspenden aus der Zivilgesellschaft. Die Spenden von Firmen haben wir <a href="https://epicenter.works/spenden-faq">gedeckelt</a>, da wir unsere Arbeit nur machen können, wenn wir unabhängig sind. Gelder aus öffentlicher Hand haben wir bis jetzt noch nie angenommen. In unserem jährlichen <a href="https://epicenter.works/transparenz">Transparenzbericht</a> findest du die genauen Zahlen. Wir sind für unsere Unabhängigkeit darauf angewiesen, möglichst viele Einzelspenden zu bekommen. Wenn du unsere Arbeit gut findest, bitte unterstütze uns <a href="https://spenden.epicenter.works">spenden.epicenter.works</a>.
					</p>
				</li>
				<li>
					<div class="avtxt">
						<h3>Wie kann ich bei euch mitmachen?</h3>
					</div>
				</li>
				<li>
					<p>
						Wir verstehen uns als Plattform und Stimme für zivilgesellschaftliches Engagement für Grund- und Freiheitsrechte im digitalen Zeitalter. Bei uns kann man ganz einfach mitmachen, indem man sich auf der <a href="https://epicenter.works/mitmachen">Mitmachen-Seite</a> anmeldet oder zum monatlich stattfindenden <a href="https://epicenter.works/tags/Veranstaltungen">Netzpolitischen Abend</a> kommt. Der Großteil unserer Arbeit wird von Ehrenamtlichen gemacht. Wir freuen uns über alle konstruktiven Menschen, die sich in ihrer Demokratie einbringen wollen.
					</p>
				</li>
				<li>
					<div class="avtxt">
						<h3>Wie funktioniert diese Website?</h3>
					</div>
				</li>
				<li>
					<p>
						Dank großartiger Menschen, die die Funktionen dieser Seite unbezahlt programmiert haben, funktioniert sie hervorragend. Im Ernst: Du kannst über diese Seite Kontakt mit Regierungsmitgliedern und Abgeordneten aufnehmen und mit ihnen über Überwachung reden. Frage sie nach einer Wirkungsfolgenabschätzung für neue Überwachungsgesetze. Frage sie nach einer Überwachungsgesamtrechnung. Frage sie, warum die Einschränkung deiner Rechte mehr Sicherheit bringen soll.
					</p>
				</li>
			</ul>

			<h2>Geschlechtergerechte Sprache</h2>
			<ul>
				<li>
					<div class="avtxt">
						<h3>Warum werden nicht alle Geschlechter angesprochen?</h3>
					</div>
				</li>
				<li>
					<p>
						Uns als Betreibern dieser Website fehlt es nicht an Sensibilität für geschlechtergerechte Sprache. Da die Kürze vor allem bei der Telefonfunktion sehr bedeutsam ist, haben wir uns schweren Herzens für das generische Maskulinum entschieden und das dann auch in den Texten der Website verwendet. Das ist ein Kompromiss. Wir bitten um Nachsicht!
					</p>
				</li>
			</ul>
		</div>
	</section>
{% endblock %}