ueberwachungspaket/views/act.py
from random import choice
from datetime import datetime, timedelta
from re import match
from flask import (Blueprint, render_template, abort, request, url_for,
                   flash, redirect)
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm.exc import NoResultFound
from config import DEBUG, FEEDBACK_NUMBER, TWILIO_NUMBERS
from database.models import (Representatives, Reminder, Mail, Sender)
from database import db_session
from ueberwachungspaket.decorators import twilio_request

mod = Blueprint("act", __name__, url_prefix="/act")
reps = Representatives()


#@mod.route("/mail/", methods=["POST"])
def mail():
    id = request.form.get("id")
    rep = reps.get_representative_by_id(id)
    firstname = request.form.get("firstname")
    lastname = request.form.get("lastname")
    mail_user = request.form.get("email")
    newsletter = True if request.form.get("newsletter") == "yes" else False

    if not all([rep, firstname, lastname, mail_user]) or not rep.contact.mail or id == "00000" or not match(r"[^@]+@[^@]+\.[^@]+", mail_user):
        abort(400)  # bad request

    name_user = firstname + " " + lastname

    try:
        sender = db_session.query(Sender).filter_by(email_address=mail_user).one()

        if newsletter:
            sender.newsletter = True
            db_session.commit()

        mail = Mail(sender, id)

        try:
            db_session.add(mail)
            db_session.commit()

            if sender.date_validated:
                # sender is authorized to send mails
                flash("Vielen Dank für Ihre Teilnahme.")
                mail.send()
                db_session.commit()
            else:
                if datetime.now() - sender.date_requested > timedelta(5):
                    # validation request expired
                    flash("Ihre Bestätigungsanfrage ist abgelaufen. Um fortzufahren, bestätigen Sie bitte den Link, den wir an {mail_user} gesendet haben.".format(mail_user=sender.email_address))
                    sender.request_validation()
                    db_session.commit()
                else:
                    # validation request needs to be confirmed
                    flash("Danke für Ihr Engagement. Um fortzufahren, bestätigen Sie bitte den Link, den wir an {mail_user} gesendet haben.".format(mail_user=sender.email_address))

        except IntegrityError:
            flash("Sie haben {rep_name} bereits eine E-Mail geschrieben.".format(rep_name=str(rep)))
            db_session.rollback()

    except NoResultFound:
        # sender never sent mail before
        sender = Sender(name_user, mail_user, newsletter=newsletter)
        db_session.add(sender)
        mail = Mail(sender, id)
        db_session.add(mail)
        db_session.commit()
        flash("Danke für Ihr Engagement. Um fortzufahren, bestätigen Sie bitte den Link, den wir an {mail_user} gesendet haben.".format(mail_user=sender.email_address))

    return redirect(url_for("act.representative", prettyname=rep.name.prettyname, _anchor="email-senden"))


#@mod.route("/validate/<hash>", methods=["GET"])
def validate(hash):
    try:
        sender = db_session.query(Sender).filter_by(hash=hash).one()

        if sender.date_validated:
            flash("Sie haben Ihre E-Mail Adresse bereits erfolgreich verifiziert.")
        elif datetime.now() - sender.date_requested > timedelta(5):
            flash("Ihre Bestätigungsanfrage ist abgelaufen. Um fortzufahren, bestätigen Sie bitte den Link, den wir an {mail_user} gesendet haben.".format(mail_user=sender.email_address))
            sender.request_validation()
        else:
            flash("Vielen Dank, Sie haben Ihre E-Mail Adresse erfolgreich verifiziert.")
            sender.validate()
            for mail in sender.mails:
                mail.send()
            db_session.commit()

    except NoResultFound:
        flash("Dieser Bestätigungslink ist ungültig.")

    return render_template("validate.html")


#@mod.route("/call/", methods=["POST"])
@twilio_request
def call(resp):
    resp.play(url_for("static", filename="audio/intro.wav"))
    resp.redirect(url_for("act.gather_menu"))


#@mod.route("/callback/", methods=["POST"])
@twilio_request
def callback(resp):
    direction = request.values.get("Direction")
    duration = request.values.get("CallDuration", 0, type=int)

    if direction == "inbound":
        number = request.values.get("From")
    else:
        number = request.values.get("To")

    try:
        reminder = db_session.query(Reminder).filter_by(phone_number=number).one()
        reminder.time_connected = reminder.time_connected + duration
        db_session.commit()
    except IntegrityError:
        db_session.rollback()
    except NoResultFound:
        pass


#@mod.route("/gather-menu/", methods=["POST"])
@twilio_request
def gather_menu(resp):
    number = request.values.get("From")

    try:
        reminder = Reminder(number)
        db_session.add(reminder)
        db_session.commit()
    except IntegrityError:
        db_session.rollback()

    with resp.gather(numDigits=1, action=url_for("act.handle_menu")) as g:
        g.play(url_for("static", filename="audio/gather_menu.wav"), loop=4)


#@mod.route("/handle-menu/", methods=["POST"])
@twilio_request
def handle_menu(resp):
    digits_pressed = request.values.get("Digits", 0, type=int)

    if digits_pressed == 1:
        resp.redirect(url_for("act.gather_reminder_time"))
    elif digits_pressed == 2:
        resp.redirect(url_for("act.gather_representative"))
    elif digits_pressed == 3:
        resp.redirect(url_for("act.info_tape"))
    elif digits_pressed == 4:
        resp.redirect(url_for("act.handle_reminder_unsubscribe"))
    elif digits_pressed == 5:
        resp.dial(FEEDBACK_NUMBER)
    else:
        resp.play(url_for("static", filename="audio/invalid.wav"))
        resp.redirect(url_for("act.gather_menu"))


#@mod.route("/gather-reminder-time/", methods=["POST"])
@twilio_request
def gather_reminder_time(resp):
    with resp.gather(numDigits=2, action=url_for("act.handle_reminder_time")) as g:
        g.play(url_for("static", filename="audio/gather_reminder_time.wav"), loop=4)


#@mod.route("/handle-reminder-time/", methods=["POST"])
@twilio_request
def handle_reminder_time(resp):
    digits_pressed = request.values.get("Digits", 0, type=int)
    number = request.values.get("From")

    if not number or number in ["+7378742833", "+2562533", "+8656696", "+266696687", "+86282452253"]:
        resp.play(url_for("static", filename="audio/handle_reminder_time_error.wav"))
    if 9 <= digits_pressed <= 16:
        reminder = db_session.query(Reminder).filter_by(phone_number=number).one()
        if reminder.time is None:
            resp.play(url_for("static", filename="audio/handle_reminder_time_set.wav"))
        else:
            if digits_pressed > datetime.now().hour and reminder.last_called.date() == datetime.today().date():
                reminder.last_called = None

            resp.play(url_for("static", filename="audio/handle_reminder_time_reset.wav"))

        reminder.time = digits_pressed
        db_session.commit()
    else:
        resp.play(url_for("static", filename="audio/handle_reminder_time_invalid.wav"))
        resp.redirect(url_for("act.gather_reminder_time"))


#@mod.route("/gather-representative/", methods=["POST"])
@twilio_request
def gather_representative(resp):
    with resp.gather(numDigits=5, action=url_for("act.handle_representative")) as g:
        g.play(url_for("static", filename="audio/gather_representative.wav"), loop=4)


#@mod.route("/handle-representative/", methods=["POST"])
@twilio_request
def handle_representative(resp):
    digits_pressed = request.values.get("Digits", "00000", type=str)
    number = request.values.get("From")
    rep = reps.get_representative_by_id(digits_pressed)

    if rep is not None and rep.contact.phone:
        reminder = db_session.query(Reminder).filter_by(phone_number=number).one()
        reminder.times_forwarded = reminder.times_forwarded + 1
        db_session.commit()

        resp.play(url_for("static", filename="audio/handle_representative_a.wav"))
        resp.play(url_for("static", filename="audio/representative/" + rep.name.prettyname + ".wav"))
        resp.play(url_for("static", filename="audio/handle_representative_c.wav"))

        if DEBUG:
            resp.dial(FEEDBACK_NUMBER, timeLimit=60, callerId=choice(TWILIO_NUMBERS))
        else:
            resp.dial(rep.contact.phone, timeLimit=3600, callerId=choice(TWILIO_NUMBERS))

        resp.play(url_for("static", filename="audio/adieu.wav"))

    else:
        resp.play(url_for("static", filename="audio/handle_representative_invalid.wav"))
        resp.redirect(url_for("act.gather_representative"))


#@mod.route("/handle-reminder-unsubscribe/", methods=["POST"])
@twilio_request
def handle_reminder_unsubscribe(resp):
    direction = request.values.get("Direction")

    if direction == "inbound":
        number = request.values.get("From")
    else:
        number = request.values.get("To")

    reminder = db_session.query(Reminder).filter_by(phone_number=number).one()
    reminder.time = None
    db_session.commit()
    resp.play(url_for("static", filename="audio/handle_reminder_unsubscribe.wav"))


#@mod.route("/gather-reminder-call/", methods=["POST"])
@twilio_request
def gather_reminder_call(resp):
    resp.play(url_for("static", filename="audio/gather_reminder_call.wav"))
    resp.redirect(url_for("act.gather_reminder_menu"))


#@mod.route("/gather-reminder-menu/", methods=["POST"])
@twilio_request
def gather_reminder_menu(resp):
    with resp.gather(numDigits=1, action=url_for("act.handle_reminder_menu")) as g:
        g.play(url_for("static", filename="audio/gather_reminder_menu.wav"), loop=4)


#@mod.route("/handle-reminder-menu/", methods=["POST"])
@twilio_request
def handle_reminder_menu(resp):
    digits_pressed = request.values.get("Digits", 0, type=int)
    number = request.values.get("To")

ueberwachungspaket/views/general.py
from random import shuffle
from json import load
from flask import Blueprint, render_template, abort, request, jsonify
from sqlalchemy import func
from sqlalchemy.exc import IntegrityError
from config import TWILIO_NUMBERS, ACTIVISM_LIST_POST_URL, ACTIVISM_LIST_POST_REFERER
from database.models import Representatives, Opinion, ConsultationSender, Activist
from database import db_session
from datetime import datetime
import requests

mod = Blueprint("general", __name__)
reps = Representatives()


@mod.route("/")
def index():
    with open("ueberwachungspaket/data/quotes_2.0.json", "r") as json_file:
        quotes = load(json_file)
    shuffle(quotes)
    consultation_count = 9143 #db_session.query(func.count(ConsultationSender.date_validated)).one()[0]
    opinions = db_session.query(Opinion).count()
    return render_template(
        "general/index.html",
        quotes=quotes,
        opinion_count=opinions,
        consultation_count=consultation_count
    )


#@mod.route("/politiker/")
def representatives():
    reps_random = reps.representatives + reps.government
    shuffle(reps_random)
    return render_template(
        "act/representatives.html",
        reps=reps_random
    )


#@mod.route("/p/<prettyname>/")
def representative(prettyname):
    rep = reps.get_representative_by_name(prettyname)
    if rep:
        return render_template(
            "act/representative.html",
            rep=rep,
            twilio_number=TWILIO_NUMBERS[0]
        )
    else:
        abort(404)


@mod.route("/weitersagen/")
def share():
    return render_template("general/share.html")


@mod.route("/unterstützer/")
def supporters():
    return render_template("general/supporters.html")


@mod.route("/faq/")
def faq():
    return render_template("general/faq.html")


@mod.route("/datenschutz/")
def privacy():
    return render_template("general/privacy.html")

#@mod.route("/join/", methods=["POST"])
def join():
    email = request.form.get('email')
    phone = request.form.get('phonenumber')

    if not email:
        abort(400)

    activist = Activist(email, phone, datetime.now())

    try:
        db_session.add(activist)
        db_session.commit()
    except IntegrityError:
        return jsonify({'status': 'error', 'reason': 'already_subscribed'})

    requests.post(ACTIVISM_LIST_POST_URL, data={'email': email}, headers={'referer': ACTIVISM_LIST_POST_REFERER})

    return jsonify({'status': 'success', 'reason': ''})

ueberwachungspaket/templates/act/representative.html
{% extends "layout.html" %}
{% set active_page = "act.representative" %}

{% block title %}
    <title>{{ rep }} | {{ config['PROJECT_NAME'] }}</title>
{% endblock title%}

{% block content %}
    <section class="column">
        <h1>{{ rep.fullname() }} ({{ rep.party.shortname }})</h1>
        <div class="profile-adjustment">
            <div class="profile {{ rep.team.prettyname }}">
                <img src="{{ url_for('static', filename='img/representative/' + rep.id + '.jpg') }}" alt="{{ rep }}" />
                <span class="team {{ rep.team.prettyname }}">{{ rep.team }}</span>
            </div>
        </div>
        <div class="row bottom">
            {% if rep.contact.facebook|length > 0 %}
            <a class="share center" href="https://www.facebook.com/{{ rep.contact.facebook }}" target="_blank">
                <div class="center"><i class="fa fa-facebook" aria-hidden="true"></i></div>
            </a>
            <a class="share center" href="https://fb.com/msg/{{ rep.contact.facebook }}" target="_blank">
                <div class="center"><i class="fb-messenger" aria-hidden="true"></i></div>
            </a>
            {% endif %}
            {% if rep.contact.twitter|length > 0 %}
            <a class="share center" href="https://twitter.com/intent/tweet?url=https%3A%2F%2Füberwachungspaket%2Eat%2F&text=Stoppt%20das%20%C3%9Cberwachungspaket%21%20%40{{ rep.contact.twitter }}&hashtags=%C3%BCberwachungspaket&related=epicenter%5Fworks%3Aepicenter%2Eworks" target="_blank">
                <div class="center"><i class="fa fa-twitter" aria-hidden="true"></i></div>
            </a>
            {% endif %}
            {% if rep.contact.mail|length > 0 %}
            <a class="share center" href="#email">
                <div class="center"><i class="fa fa-envelope-o" aria-hidden="true"></i></div>
            </a>
            {% endif %}
            {% if rep.contact.phone|length > 0 %}
            <a class="share center" href="#anrufen">
                <div class="center"><i class="fa fa-phone" aria-hidden="true"></i></div>
            </a>
            {% endif %}
        </div>
    </section>
    {% if rep.contact.phone|length > 0 %}
    <section id="anrufen">
        <h2><a name="anrufen"></a><i class="fa fa-phone fa-lg" aria-hidden="true"></i>Noch nie war es einfacher, mit deinen Abgeordneten zu sprechen!</h2>
        <div id="call" class="row items3 row-space centertext">
            <div>
                <i class="fa fa-mobile fa-5x" aria-hidden="true"></i>
                <h3>Hotline anrufen</h3>
                <p>Unter <strong><a href="tel:{{ twilio_number }}">{{ twilio_number }}</a></strong> ist dein direkter Draht ins Parlament. Unsere Hotline macht es so einfach wie noch nie, Politiker zu überzeugen.</p>
            </div>
            <div>
                <i class="fa fa-reply-all fa-5x" aria-hidden="true"></i>
                <h3>Politiker auswählen</h3>
                <p>Der Code <strong>{{ rep.id }}</strong> verbindet dich direkt mit dem Büro von {{ rep }}.</p>
            </div>
            <div>
                <i class="fa fa-comments fa-5x" aria-hidden="true"></i>
                <h3>Überwachungspaket verhindern</h3>
                <p>Sag' den Politikern, dass du nicht überwacht werden willst. Frage nach Belegen, wieso diese Überwachungsmaßnahmen uns sicherer machen sollen.</p>
            </div>
        </div>
        <h2>Beispielgespräch</h2>
        <div class="chat container">
            <ul>
                <li>
                    <div class="avatar"><img src="{{ url_for('static', filename='img/conversation/' + rep.party.handle + '.png') }}"></div>
                    <div class="avtxt">Hallo, Sie sprechen mit dem {% if rep.is_government %}Büro von {{ rep.name.firstname }} {{ rep.name.lastname }}{% else %}{{ rep.party.shortname }}-Parlamentsklub{% endif %}.</div>
                </li>
                <li>
                    <p>Guten Tag, meine Name ist ... Ich würde gerne mit {{ rep.name.firstname }} {{ rep.name.lastname }} sprechen.</p>
                </li>
                <li>
                    <div class="avatar"><img src="{{ url_for('static', filename='img/conversation/' + rep.party.handle + '.png') }}"></div>
                    <div class="avtxt">{% if rep.is_female %}Die{% else %}Der{% endif %} ist gerade leider nicht da, kann ich {% if rep.is_female %}ihr{% else %}ihm{% endif %} etwas ausrichten?</div>
                </li>
                <li>
                    <p>Ja, bitte fragen Sie {% if rep.is_female %}sie{% else %}ihn{% endif %}, wie das neue Überwachungspaket uns sicherer machen wird und teilen Sie {% if rep.is_female %}ihr{% else %}ihm{% endif %} mit, dass ich als normaler Bürger über diese Ausweitung des Überwachungsstaats sehr besorgt bin.</p>
                </li>
                <li>
                    <div class="avatar"><img src="{{ url_for('static', filename='img/conversation/' + rep.party.handle + '.png') }}"></div>
                    <div class="avtxt">Danke, ich werde das weitergeben.</div>
                </li>
                <li>
                    <p>Vielen Dank für das Gespräch! Ich würde mich sehr über eine Antwort per E-Mail oder einen Rückruf freuen.</p>
                </li>

            </ul>
        </div>
    </section>
    {% endif %}
    {% if rep.contact.mail|length > 0 %}
    <section id="email-senden">
        <h2><a name="email"></a><i class="fa fa-envelope-o fa-lg" aria-hidden="true"></i> E-Mail senden</h2>
        <form id="mail" autocomplete="off" class="shrunk" action="{{ url_for('act.mail') }}" method="post">
            {% with messages = get_flashed_messages() -%}
                {% if messages -%}
                    {% for message in messages -%}
                        <p>{{ message }}</p>
                    {% endfor -%}
                {% endif -%}
            {% endwith -%}
            <div class="row row-space align-left">
                <div class="column">
                    <label for="mail-firstname">Vorname *</label>
                    <input type="text" name="firstname" id="mail-firstname" required="required">
                </div>
                <div class="column">
                    <label for="mail-lastname">Nachname *</label>
                    <input type="text" name="lastname" id="mail-lastname" required="required">
                </div>
                <div class="column">
                    <label for="mail-email">E-Mail *</label>
                    <input type="email" name="email" id="mail-email" required="required">
                </div>
                <div class="column">
                    <label for="mail-newsletter" class="space"><input type="checkbox" name="newsletter" id="mail-newsletter" value="yes">Newsletter abonnieren</label>
                </div>
            </div>
            <p class="small">* Pflichtfeld</p>
            <input type="hidden" name="id" value="{{ rep.id }}" />
            <div class="textarea">{{ config['MAIL_REPRESENTATIVE']|e }}</div>
            <button class="btn btn-default">Senden</button>
            <p class="center small indent">Wenn du diese Nachricht abändern möchtest, kannst du die E-Mail <a href="mailto:{{ rep.contact.mail }}?subject=%C3%9Cberwachungspaket">direkt</a> verschicken.</p>
        </form>
    </section>
    {% endif %}

<script>
    MailNameTo = "{{ rep }}";
    MailSalutation = "{{ rep.salutation }}";
</script>
{% endblock %}

ueberwachungspaket/templates/act/representatives.html
{% extends "layout.html" %}
{% set active_page = "act.representatives" %}

{% block title %}
    <title>Draht zu deinen Politikern | {{ config['PROJECT_NAME'] }}</title>
{% endblock title %}

{% block content %}
    <section id="aktiv">
        <h1>Draht zu deinen Politikern</h1>
        <h2>Überzeuge deine Abgeordneten, dass wir ein echtes Sicherheitspaket brauchen und kein Überwachungspaket</h2>
        <div id="filter" class="column">
            <form id="importance" class="btn-group row" autocomplete="off">
                <input id="reps-important" type="radio" name="importance" checked="checked">
                <label for="reps-important">thematisch Zuständige</label>
                <input id="reps-all" type="radio" name="importance">
                <label for="reps-all">alle Politiker</label>
            </form>
            <form id="parties" class="btn-group row" autocomplete="off">
                <input id="spoe" type="checkbox">
                <label for="spoe">SPÖ</label>
                <input id="oevp" type="checkbox">
                <label for="oevp">ÖVP</label>
                <input id="fpoe" type="checkbox">
                <label for="fpoe">FPÖ</label>
                <input id="gruene" type="checkbox">
                <label for="gruene">GRÜNE</label>
                <input id="neos" type="checkbox">
                <label for="neos">NEOS</label>
                <input id="frank" type="checkbox">
                <label for="frank">FRANK</label>
                <input id="none" type="checkbox">
                <label for="none">parteilos</label>
            </form>
            <form id="teams" class="btn-group row" autocomplete="off">
                <input id="liberty" type="checkbox">
                <label for="liberty"><span class="glyph liberty">&#9724;</span> Team Grundrechte</label>
                <input id="spy" type="checkbox">
                <label for="spy"><span class="glyph spy">&#9724;</span> Team Überwachung</label>
                <input id="unknown" type="checkbox">
                <label for="unknown"><span class="glyph unknown">&#9724;</span> Unbekannt</label>
            </form>
            <form id="states" class="btn-group row" autocomplete="off">
                <input id="state-b" type="checkbox">
                <label for="state-b">Bgld.</label>
                <input id="state-k" type="checkbox">
                <label for="state-k">Ktn.</label>
                <input id="state-n" type="checkbox">
                <label for="state-n">NÖ</label>
                <input id="state-o" type="checkbox">
                <label for="state-o">OÖ</label>
                <input id="state-s" type="checkbox">
                <label for="state-s">Sbg.</label>
                <input id="state-st" type="checkbox">
                <label for="state-st">Stmk.</label>
                <input id="state-t" type="checkbox">
                <label for="state-t">T</label>
                <input id="state-v" type="checkbox">
                <label for="state-v">Vbg.</label>
                <input id="state-w" type="checkbox">
                <label for="state-w">W</label>
            </form>
            <form id="name" class="btn-group row" autocomplete="off">
                <input type="text" size="60" placeholder="Namenssuche" />
            </form>
        </div>
        <div id="representatives" class="row">
            {% for rep in reps %}
            <a class="representative {% if not rep.important %}invisible{% endif %}" href="{{ url_for('general.representative', prettyname=rep.name.prettyname) }}" data-firstname="{{ rep.name.firstname }}" data-lastname="{{ rep.name.lastname }}" data-party="{{ rep.party.prettyname }}" data-team="{{ rep.team.prettyname }}" data-state="{{ rep.state }}" data-important="{{ rep.important }}">
                <div class="column">
                    <div class="name">{{ rep.name.lastname }}</div>
                    <div class="party">{{ rep.party.shortname }}</div>
                </div>
                <div class="overlay {{ rep.team.prettyname }}"></div>
                <img src="{{ url_for('static', filename='img/representative-small/' + rep.id + '.jpg') }}" alt="" />
            </a>
            {% endfor %}
        </div>
        <p class="center small indent">Die Zuordnung der Politikerinnen und Politiker zu den einzelnen Teams erfolgte durch den Verein epicenter.works auf Basis von Aussagen der Personen und Parteien. Sollte die hier getroffene Zuordnung für oder gegen das geplante Überwachungspaket zu stimmen nicht korrekt sein, treten Sie mit uns in Kontakt.</p>
        <p class="center small indent">Kontaktdaten der <a href="{{ url_for('static', filename='data/representatives.csv') }}">Abgeordneten</a> und <a href="{{ url_for('static', filename='data/representatives.csv') }}">Regierungsmitglieder</a> als CSV.</p>
    </section>
{% endblock %}

ueberwachungspaket/templates/act/validate.html
{% extends "layout.html" %}

{% block title %}
    <title>E-Mail Verifikation | {{ config['PROJECT_NAME'] }}</title>
{% endblock title%}

{% block content %}
    <section>
        <h2>E-Mail Verifikation</h2>
        {% with messages = get_flashed_messages() -%}
            {% if messages -%}
                {% for message in messages -%}
                    <p>{{ message }}</p>
                {% endfor -%}
            {% endif -%}
        {% endwith -%}
    </section>
{% endblock %}